### ISSUE TITLE
https://github.com/eclipse-ee4j/glassfish/issues

### ISSUE THREAD

**Issue by caim2015** [eclipse-ee4j/glassfish#23078] opened 2020-06-05 04:02 UTC
## Environment Details
* GlassFish Version (and build number):V5
* JDK version:8

app:
[demoappNoCharset.zip](https://github.com/eclipse-ee4j/glassfish/files/4733808/demoappNoCharset.zip)

home.xhtml
`
<h:form>        
        <h:inputText id = "inputName" value = "#{userData.name}">       
        </h:inputText>                 
        <h:commandButton id="getCode" value="submit" action="#{userData.getVisible()}" />
		<br/>
		<br/>
		<table width="120" border="0" cellpadding="0" cellspacing="0" style="#{userData.isVisible()}">
		<tr>          
           <td>
            <h:outputText id="outputText" value="#{userData.name}"/>
            </td>
        </tr>
		</table>              
      </h:form>
   </h:body>
`
case1)
Steps to reproduce:

1.deploy the demoappNoCharset.war
2.In browser open page by the following address:
    http://ip:port/demoappNoCharset/home.xhtml
3.input multibyte characters(for example:テスト) in input box.
4.click "submit".
When click "submit",the error characters is displayed.

Although,"default-charset" is set corresponding "SJIS" in glassfish-web.xml works fine,but isn't it a bug?

case2)
app:
[demoappFilter.zip](https://github.com/eclipse-ee4j/glassfish/files/4733809/demoappFilter.zip)

home.xhtml
`
<h:form>        
    <h:inputText id = "inputName" value = "#{userData.name}">
        <f:ajax event="focus" render="@this" listener="#{userData.welcomeMessage()}" />
    </h:inputText>                 
    <h:commandButton id="getCode" value="submit" action="#{userData.getVisible()}" /><br/>
	<br/>
	<table width="120" border="0" cellpadding="0" cellspacing="0" style="#{userData.isVisible()}">
		<tr>          
           <td>
            <h:outputText id="outputText" value="#{userData.name}"/>
           </td>
        </tr>
	</table>                          
</h:form>
`
EncodingFilter.java
<pre>
@WebFilter("/*")
public class EncodingFilter implements Filter {
	
	public void init(FilterConfig fConfig) throws ServletException {}
	
	public void destroy() {}

	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
		
		request.setCharacterEncoding("SJIS");				       
		chain.doFilter(request, response);
	}
}
</pre>
Steps to reproduce:
1.deploy the demoappFilter.war
2.In browser open page by the following address:
    http://ip:port/demoappFilter/home.xhtml
3.input multibyte characters(for example:テスト) in input box.
4.click the blank of the page to lose focus.(Ajax event triggered)

When lose focus,the error characters is displayed.

Although,when remove the Filter works fine,but isn't it a bug?

**Comment by gerdogdu** [comment] 2020-07-06 11:03
I think it is related with # https://github.com/eclipse-ee4j/glassfish/issues/23108

**Comment by gerdogdu** [comment] 2020-07-06 11:05
Duplicate of #23108

**Closed** 2020-07-18 17:08 UTC
