### ISSUE TITLE
Misleading position of "5.1.0" branch

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish#22936] opened 2020-03-03 10:10 UTC
> created branch https://github.com/eclipse-ee4j/glassfish/tree/5.1.0 from master.

But there already is [5.1.0-BRANCH](https://github.com/eclipse-ee4j/glassfish/tree/5.1.0-BRANCH), created as
> 5.1.0 maintenance work will work of the 5.1.0 tag.

Please consider deleting new [5.1.0](https://github.com/eclipse-ee4j/glassfish/tree/5.1.0) one.

_Originally posted by @pzygielo in https://github.com/eclipse-ee4j/glassfish/issues/22874#issuecomment-575777703_

**Comment by bshannon** [comment] 2020-03-04 19:40
Let me make sure I understand...

The 5.1.0 tag is correct.
The 5.1.0-BRANCH branch was created from that tag correctly.
Someone created a new 5.1.0 branch.
Who created it?
Was it created from the 5.1.0 tag?

**Comment by pzygielo** [comment] 2020-03-04 19:54
> Let me make sure I understand...
> 
> The 5.1.0 tag is correct.

right

> The 5.1.0-BRANCH branch was created from that tag correctly.

right

> Someone created a new 5.1.0 branch.
> Who created it?
> Was it created from the 5.1.0 tag?

Answers in _Originally posted by @pzygielo in #22874 (comment)_
> > Was it created from the 5.1.0 tag?

No.

**Comment by bshannon** [comment] 2020-03-04 20:23
Ok, if I'm decoding this correctly, it looks like @arjantijms created the branch.

@arjantijms why did you create a new 51.0 branch?  Can you delete it and
work off of the 5.1.0-BRANCH branch?

**Comment by pzygielo** [comment] 2020-05-27 06:13
@arjantijms could you check it please?

**Comment by dboggs95** [comment] 2020-06-06 15:30
I think there is a problem no matter what. 
- 5.1.0 was released on January 28, 2019.
- The branch named "5.1.0" was created on January 13, 2019 when master was updated to 6.0.0, and although the release was several days after this, this probably means that the release was code from right before this branch was created.
- The branch named "5.1.0" was intended for maintenance of that version.
- The branch named "5.1.0-BRANCH" already existed at this time. 
- The branch named "5.1.0" is 358 commits behind master.
- The branch named "5.1.0-BRANCH" is 14 commits ahead, 469 commits behind master.
- That puts "5.1.0" 111 commits ahead of "5.1.0-BRANCH" and "5.1.0-BRANCH" 14 commits ahead of "5.1.0", and the latter was last updated very recently. 

It looks to me like the developers didn't enforce which branch was correct themselves. It seems like there should be a release/5.1.0 that is frozen, and a release/5.1.1 that is getting bugfixes. These branches were probably supposed to map onto that scheme, but now, if someone wants to create a  5.1.1 release, he'd have to merge both branches together. 

On top of that, there are some things that need fixed in the UI (maybe it works on Linux, but on Windows it's very buggy) and a fix is required for Windows builds. 
- The Windows build issue makes it impossible to build on Windows without commenting out a couple JUnit tests. Someone said he'd make a PR for this, forked Glassfish, and never did it. 
[Issue#22730](https://github.com/eclipse-ee4j/glassfish/issues/22730)
- In the UI, there is an error everytime one opens a page with a table. (Haven't checked for a PR to this issue yet.)
- In the UI, there is a defect when adding properties to a JNDI DataSource. The screen gets messed up, and sometimes erases all your properties. (Haven't checked for a PR to this issue yet.)
- In the UI, there is a defect making it is impossible to deploy a war file manually. There is a very simple PR for this but it has been open for a year, and only got a approved 2 days ago. [Issue#22739](https://github.com/eclipse-ee4j/glassfish/issues/22739)
All of these issues are very apparent after just a few weeks of using Glassfish. Ideally, these would all be fixed in a 5.1.1 release that resulted from a maintenance branch.

In my humble opinion, this seems very disorganized, and this is how it should be solved. 
1. Branch out of "5.1.0" and create "release/5.1.1". 
2. Branch out of "release/5.1.1" and create "release/5.1.0". Rewind that branch all the way back to the last commit in "5.1.0" before that version was released. Never touch that branch again.
3. Find the 14 extra commits in "5.1.0-BRANCH" and move them into "release/5.1.1". 
4. Delete "5.1.0" and "5.1.0-BRANCH".
4. Fix some of the most obvious issues in version 5.1.0 in "release/5.1.1" and create a release candidate.
5. Continue this best practice of using a release/* for new versions and fixes in the future.

**Comment by pzygielo** [comment] 2020-09-06 13:14
@arjantijms Could you comment that "5.1.0" is really needed (not "5.1.0-BRANCH" which I know it is), or remove it, please?

**Closed** 2020-09-13 08:01 UTC

**Comment by pzygielo** [comment] 2023-08-26 14:28
Just for the record: 5.1.0 points at 7c3831024d18ce975f88258a2f7f6dbebd69bed8.
