### ISSUE TITLE
GlassFish 5.1 asadmin start-domain is failing with NullPointerException

### ISSUE THREAD

**Issue by peddi-dev** [eclipse-ee4j/glassfish#22842] opened 2019-09-25 13:53 UTC
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"
GlassGish 5.1 asadmin start-domain is failing with NullPointerException 

## Environment Details
* GlassFish Version (and build number): 5.1
https://www.eclipse.org/downloads/download.php?file=/glassfish/glassfish-5.1.0.zip
* JDK version: 11.0.4
* OS: MacOS 10.14.6
* Database: N/A

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"

as-install/bin/asadmin start-domain command failing with NullPointerException

[//]: # "State if the problem is easily reproducible or happens intermittently"
Reproducible

[//]: # "Include stack traces or command outputs"
$as-install/bin/asadmin start-domain 
Exception in thread "main" java.lang.NullPointerException
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.initializeServiceLocator(AbstractModulesRegistryImpl.java:128)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.newServiceLocator(AbstractModulesRegistryImpl.java:120)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:194)
	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:200)
	at com.sun.enterprise.module.single.StaticModulesRegistry.createServiceLocator(StaticModulesRegistry.java:64)
	at com.sun.enterprise.admin.cli.CLIContainer.getServiceLocator(CLIContainer.java:193)
	at com.sun.enterprise.admin.cli.CLIContainer.getLocalCommand(CLIContainer.java:231)
	at com.sun.enterprise.admin.cli.CLICommand.getCommand(CLICommand.java:207)
	at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:347)
	at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:282)
	at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:33)

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
run the following command
as-install/bin/asadmin start-domain 
[//]: # "Provide sample code/application if relevant"
N/A
## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
Trying Java 11 with GlassFish.
[//]: # "Please choose one each Type, Component, and Priority label"
GlasshFish 5.1 dowloaded location 
https://www.eclipse.org/downloads/download.php?file=/glassfish/glassfish-5.1.0.zip

**Comment by Cousjava** [comment] 2019-09-25 13:59
Glassfish 5.1 does not work with JDK9+, this has been already reported. Closing as duplicate of #21588

**Closed by Cousjava** 2019-09-25 13:59 UTC
