### ISSUE TITLE
Glassfish zip archive has some extra dependencies.

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#23279] opened 2020-11-16 05:32 UTC
Before Glassfish 6.0 RC2 was published on the maven central, I have downloaded the archive file directly and installed it into my maven local repository, all worked well.

In my sample project, I was using a dependency plugin to retrieve the archive file.

https://github.com/hantsy/jakartaee9-starter-boilerplate/blob/arquillian_update/pom.xml#L820-L845

But I found the RC2 is available in the maven central now, and added a Github action workflow to run the testing task automatically, it failed due to an extra dependency.

```bash
 Error:  Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:unpack (unpack) on project jakartaee9-starter-boilerplate: Unable to find/resolve artifact.: Failed to read artifact descriptor for org.glassfish.main.distributions:glassfish:zip:6.0.0-RC2: Could not find artifact org.glassfish.tyrus:tyrus-bom:pom:2.0.0-RC1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

see: https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/40/checks?check_run_id=1404528172

I have checked the pom file of `org.glassfish.main.distributions:glassfish`, it includes some other extra dependencies but not available in the Maven repository now.

In my mind, the zip archive can be downloaded as a general archive, can work standalone and no need any dependencies.

**Comment by smillidge** [comment] 2020-11-22 16:16
Problem is the GlassFish project does not control these other projects and can't really go through and check that everything is in central that we depend on. Ultimately the distribution is a binary which can be unzipped and should work to run GlassFish. I'm not sure what job you are running to hit an issue.

**Comment by hantsy** [comment] 2020-11-23 02:46
I think the glassfish zip dist archive **should** not depend on others in its *pom.xml*.

**Comment by smillidge** [comment] 2020-11-23 10:36
Could you provide more detail on what you are trying to do step by step. I'm not sure what the problem is from your description.

**Comment by smillidge** [comment] 2020-11-23 10:44
As far as I can see the zip distribution only has 4 optional zip dependencies https://search.maven.org/artifact/org.glassfish.main.distributions/glassfish/6.0.0-RC2/glassfish-distribution

**Comment by hantsy** [comment] 2020-11-23 12:47
It is simple, I was using the  Maven dependency plugin to prepare a copy of Glassfish for my Arquillian test.

```xml
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>${maven-dependency-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>unpack</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>unpack</goal>
                                </goals>
                                <configuration>
                                    <artifactItems>
                                        <artifactItem>
                                            <groupId>org.glassfish.main.distributions</groupId>
                                            <artifactId>glassfish</artifactId>
                                            <version>${glassfish.version}</version>
                                            <type>zip</type>
                                            <overWrite>false</overWrite>
                                            <outputDirectory>${project.build.directory}</outputDirectory>
                                        </artifactItem>
                                    </artifactItems>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```
When running the test, the `unpack` goal will be executed in the maven's lifecycle and got the dependency resolving error.

**Comment by smillidge** [comment] 2020-11-23 14:18
OK but I don't understand why. I'm no maven maven.

**Comment by hantsy** [comment] 2020-11-23 16:24
I do not understand why the `unpack` will resolve the dependencies.  And I also do not know why the optional(I assumed it is optional ) dep `org.glassfish.tyrus:tyrus-bom:pom:2.0.0-RC1`(also part of Glassfish project, the maven publishtion is done a CI job???) is **not available** in the Maven central.

**Comment by smillidge** [comment] 2020-11-23 17:15
Tyrus is included in the zip download as everything required to run GlassFish is in the zip. I downloaded the zip from maven central and ran it up fine manually. I don't know why maven is doing a deep scan of the dependencies just to unzip a file!

**Comment by pzygielo** [comment] 2020-11-23 18:43
@hantsy 
> I do not understand why the `unpack` will resolve the dependencies

Raise you concerns regarding plugin at proper place: http://maven.apache.org/plugins/maven-dependency-plugin/project-info.html

As a workaround for referenced dependencies missing in central - add staging repository to your project
```xml
        <repository>
            <id>sonatype-nexus-staging</id>
            <name>Sonatype Nexus Staging</name>
            <url>https://jakarta.oss.sonatype.org/content/repositories/staging/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
```
and glassfish 6-RC2 will be unpacked, as everything will be solved.
This [pom.xml](https://gist.github.com/pzygielo/2fe4f8a35d910b372fa4c8ee7d8a6d5f) (extracted from https://github.com/hantsy/jakartaee9-starter-boilerplate) shows that.
Eventually - once final GF is published - such repository will hopefully not be needed. It won't solve issue raised here, but should help with your project.

**Comment by romain-grecourt** [comment] 2020-11-23 19:46
Optional dependencies are not exposed when resolving the artifact as a dependency. Since the glassfish distribution only has optional dependencies, it mean it effectively does not have any dependency.

The error you are getting is related to the POM resolution, the parent pom imports the Tyrus bom, and it is not available in Maven Central.

**Comment by hantsy** [comment] 2020-11-24 03:23
@pzygielo  This solution resolved my problem, thanks.
My arquillain glassfish PR is passed finally, https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/40/commits/599a661326875a2fed6d1870ed9ecbfaf5433851.

**Comment by hantsy** [comment] 2020-11-24 03:31
@romain-grecourt Thanks. 

>The error you are getting is related to the POM resolution, `the parent pom imports the Tyrus bom`, and it is not available in Maven Central.

I used the dependency plugin frequently, I know the `copy/copy dependencies` resolve dependencies as general, and there is also an option to exclude transitive resolving. But in my experience, the `unpack` works like a combination of "download" and "unzip" directly.  Thanks for your explanation.

**Closed** 2020-12-29 14:27 UTC
