### ISSUE TITLE
Some options in domain.xml are mutually exclusive between JDK 8 and JDK 11.

### ISSUE THREAD

**Issue by hs536** [eclipse-ee4j/glassfish#22884] opened 2020-01-27 12:28 UTC
The current 5.1.0-run-with-JDK11 branch allows starting on JDK 11, but not JDK 8.  
  
I'm reconsidering to make GlassFish work with JDK 8 as well as JDK 11.  
First time, I thought I could implement it just like Payara Server or Maven.  
But now, I'm thinking about whether this is really appropriate...  
  
* Idea 1:(Now implementing: https://github.com/hs536/glassfish/commit/b5cbd833375af72949cfbb5328c916758a408f98 )
  Prefix the version range of JDK to the JVM option and filter them when reading domain.xml.
  ```
  domain.xml:
    <java-config>
      <jvm-options>[,8]-Djava.endorsed.dirs=XXX</jvm-options>
      <jvm-options>[9,]--add-opens=XXX</jvm-options>
      :
  ```
  + pros)
    - Only one source file needs to be managed.
  + cons)
    - This means that domain.xml contains JVM options that are not actually enabled on JDK 8 or JKD 11.
    - I think we should explain the meaning of this prefix to GlassFish users in documents or the like.
  
* Idea 2:
  Prepare a domain.xml for JDK8 (such as domain-lte-jdk8.xml) file and replace domain.xml when GlassFish start on JDK8. (On first time only)
  ```
  when user execute start-domain on JDK8 on first time,
    1. if static initialized_flag is false
    2.   if run on JDK8
    3.     replace domain-lte-jdk8.xml to domain.xml
    4.   change initialized_flag to true
    5. read domain.xml
  ```
  + pros)
    - GlassFish users can use domain.xml as before.
  + cons)
    - We'll end up managing multiple domain.xml files.
  
* Idea 3:
  Prepare a domain.xml for JDK8 (such as domain-lte-jdk8.xml) file and replace domain.xml when create-domain is executed with --jdk8 option.
  + pros)
    - GlassFish users can use domain.xml as before.
  + cons)
    - GlassFish users who want to run GlassFish on JDK 8 will have to re-create the domain.
    - We'll end up managing multiple domain.xml files.
  
* Idea4:
  Create a new profile for JDK 8 such as glassfish-jdk8.zip
  + pros
    - GlassFish users can use domain.xml as before.
    - There is no need to implement JDK version branching in scripts such as wsimport command.
  + cons
    - We'll end up managing multiple domain.xml files and command scripts.
  
Do you have any other ideas?
Suggestions and comments would be greatly appreciated.

**Comment by bshannon** [comment] 2020-01-28 01:30
Please move this discussion to the glassfish-dev mailing list, where it's more likely to get
the attention it deserves.

I'm not at all convinced that it's worth the effort to make GlassFish work on both JDK 8 and JDK 11.
Part of the problem is that it will require *every* component that's used in GlassFish to work on
both JDK 8 and JDK 11.  This might be especially complicated for those components that replace
JDK 8 components since they won't really replace them when using the jakarta.* namespace.
Will two versions of JAX-WS / Jakata XML Web Services coexist on JDK 8?

This is not just about you doing the work to handle JVM options.  This is about every other
component committing to do the work to run on JDK 8, and you committing to do whatever else
it takes to make all these components work, which is likely much more than just handling JVM
options.

**Comment by bshannon** [comment] 2020-01-28 01:55
I've been trying to catch up on my email and I just noticed a few items on the glassfish-dev
list that talked about running GlassFish on both JDK 8 and JDK 11.  They were minor items
unrelated to the subject of the messages so I didn't really notice them at the time.

In any event, I think more attention needs to be brought to this issue.  I fear it's a bigger project
than anticipated.

Unfortunately, I'm also looking at the other side of this equation, which is whether the Jakarta EE 9
compatibility requirements will require that GlassFish, being the first Compatible Implementation,
will be required to run on JDK 8 as well as JDK 11.

**Comment by hs536** [comment] 2020-01-28 06:58
Thank you for pointing it out. I'd like to send this discussion to the glassfish-dev mailing list soon.

**Comment by m0mus** [comment] 2020-01-28 15:03
IMHO, we should drop JDK8 support.

**Comment by russgold** [comment] 2020-01-28 15:07
Oracle products are using parts of Glassfish and require JDK8 support.

**Comment by bshannon** [comment] 2020-01-29 04:11
> Oracle products are using parts of Glassfish and require JDK8 support.

Any Oracle product that wants to run the same binaries on JDK 8 and JDK 11
has the same problem as GlassFish in this scenario.  They need to get commitments
from all the component suppliers to work on both JDK 8 and JDK 11.

We might be able to handle this for the few GlassFish components that are
used in other Oracle products, but I don't think we're prepared to sign up to
do it for all components.  And externally developed components are especially
an issue.  No one I've talked to has committed to doing this yet.

**Comment by smillidge** [comment] 2020-02-17 18:16
I think for GlassFish 6.x we should drop JDK 8 support. I also don't think we should support JDK 11 on GlassFish 5.x. Payara 5 has a way to manage this but tbh it is a real pain and ultimately also requires multiple supported branches. I don't think there is the bandwidth to do this in the GlassFish project.

**Comment by russgold** [comment] 2020-02-17 18:19
Which code will not work in both JDKs? That is, how big is the problem we’d avoid by not having a single release of Glassfish ever support both JDK8 and JDK11?

**Comment by hs536** [comment] 2020-02-18 05:08
> I think for GlassFish 6.x we should drop JDK 8 support.

I think so, too.

> I also don't think we should support JDK 11 on GlassFish 5.x. Payara 5 has a way to manage this but tbh it is a real pain and ultimately also requires multiple supported branches. I don't think there is the bandwidth to do this in the GlassFish project.

At the least, Fujitsu engineers (including engineers who are not committers,) are willing to maintain the branch (GF5.1+ on both JDK 8 and JDK 11). It should also be a valuable branch for vendors who already have or are trying to provide products that support EE8 compatibility (on JDK 8) and JDK 11.

It took a lot of effort a while ago, but now, some projects already have releases in the form of multi-release jars, so I think there are not many cases where unique branches are needed. We only need to create a branch from the tag (before the namespace was migrated) if we need to modify it to make it work on JDK 8.

**Comment by smillidge** [comment] 2020-02-18 11:17
The reason we introduced support for JDK dependent options in the domain.xml for Payara was actually for the grizzly-npn bootstrap support as in JDK 8 different jars are needed depending on different JDK 8 versions. However that may have settled down now.

**Comment by bshannon** [comment] 2020-03-08 18:51
> Which code will not work in both JDKs? That is, how big is the problem we’d avoid by not having a single release of Glassfish ever support both JDK8 and JDK11?

The problem may be more theoretical than actual, but that's part of the problem.
Every component, whether developed in the GlassFish repo or developed outside
the GlassFish repo, needs to commit to supporting both JDK 8 and JDK 11 with a
single release.  Getting those commitments from every component, and determining
what involved in supporting this, is a lot of work.  In some cases we might get lucky
and it might just work, or might appear to just work.  But we're not trying to get lucky,
we're trying to be correct, and that's harder.

I agree that, at least for now, supporting only JDK 11 is enough.  We need to start
making that transition ASAP.  If we have time in the future, we can go back and
reevaluate the effort required to support JDK 8 as well, and try to get those
commitments from all the external components.

**Comment by Kunzol** [comment] 2020-08-09 08:45
For idea number 1, why not using XML attributes instead of creating a new kind of "language" inside the node?

domain.xml:
```
  <java-config>
    <jvm-options jdk="8">--Djava.endorsed.dirs=XXX</jvm-options>
    <jvm-options jdk="9">--add-opens=XXX</jvm-options>
    :
```

or one level up: 
```
  <java-config jdk="8">
    <jvm-options>--Djava.endorsed.dirs=XXX</jvm-options>
   :
 </java-config>
 <java-config jdk="9">
    <jvm-options>--add-opens=XXX</jvm-options>
    :
 </java-config>
```

**Comment by smillidge** [comment] 2021-02-26 09:41
I will close this as we decided to only support JDK 11 from 6.1 onwards

**Closed by smillidge** 2021-02-26 09:41 UTC
Labels: JDK11 Upgrade
