### ISSUE TITLE
Can´t deploy applications from Web Console [deploy origPath is NULL]

### ISSUE THREAD

**Issue by eldiegos** [eclipse-ee4j/glassfish#22739] opened 2019-03-21 17:23 UTC
## Environment Details
* GlassFish Version (and build number):  Open Source Edition 5.1.0 (build default-private)

* JDK version: Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

* OS: Ubuntu 18.04.2 LTS
* Database: none

### Can´t deploy a war application from web console
**Glassfish Log**
```
[2019-03-21T18:18:07.185+0100] [glassfish 5.1] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=51 _ThreadName=admin-listener(5)] [timeMillis: 1553188687185] [levelValue: 800] [[
  GUI deployment: uploadToTempfile]]

[2019-03-21T18:18:07.188+0100] [glassfish 5.1] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=51 _ThreadName=admin-listener(5)] [timeMillis: 1553188687188] [levelValue: 800] [[
  deploy(): origPath is NULL]]

```

 **Screenshot**
![fail_deploy](https://user-images.githubusercontent.com/47030141/54771397-7865dd80-4c05-11e9-9810-ffbc8de22cdb.png)

## Steps to reproduce

1. Go to Applications -> Deploy
2. Select Packaged File to Be Uploaded to the Server option
3. Select war file
4. Deployment fails. GUI internal error: Archive Path is NULL

## Impact of Issue
 It´s quite annoying becase i have to upload the file with sftp and then select the option of local packaged file in glassfish server.

**Comment by scipio11** [comment] 2019-03-22 12:18
Having the same problem.
Also  `﻿
json.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
com_sun_faces_ajax.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
json.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
com_sun_faces_ajax.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
adminjsf.js:705 Uncaught TypeError: tree.clearAllHighlight is not a function
    at Object.clearTreeSelection (adminjsf.js:705)
    at index.jsf:191
index.jsf:194 Uncaught ReferenceError: Invalid left-hand side in assignment
browser.js:30 Uncaught SyntaxError: Unexpected token .` 
error in chrome developers tools

**Comment by gilvangobbato** [comment] 2019-04-10 13:26
Having the same problem

**Comment by duartejc** [comment] 2019-05-02 13:47
The same here

**Comment by vschimanski** [comment] 2019-05-02 19:36
confirmed on my side as well, have the same problem.

**Comment by mferretti** [comment] 2019-05-06 15:06
same here

**Comment by nambrocano** [comment] 2019-05-07 23:24
I think problem is in UploadFrame.jsf:
`<form id="form" class="form" method="post" action="/common/applications/uploadFrame.jsf" enctype="application/x-www-form-urlencoded">`
and could be:
`<form id="form" class="form" method="post" action="/common/applications/uploadFrame.jsf" enctype="multipart/form-data">`
I change it into firefox and I can upload applications without error.

**Comment by nambrocano** [comment] 2019-05-07 23:55
Code in uploadFrame.jsf:
` <sun:form id="form">`
I probe to change it to:
` <sun:form id="form" enctype="multipart/form-data">` 
in uploadFrame.jsf console-common.jar file. And it works.

**Comment by Megnatis** [comment] 2019-05-12 21:54
Having the same problem

**Comment by joaolfb** [comment] 2019-05-13 11:09
Same problem here.
Tried "nambrocano" solution and it seems to work fine.

**Comment by bshannon** [comment] 2019-05-15 19:50
@arjantijms, can you please verify that the fix above is correct?

**Comment by alyona-** [comment] 2019-07-05 15:06
> и может быть:

А где найти данный файл?

**Comment by mheydem** [comment] 2019-07-08 12:00
> 
> 
> @arjantijms, can you please verify that the fix above is correct?

Downloaded release 5.1.0 and modified <sun:form id="form"> to <sun:form id="form" enctype="multipart/form-data"> in console-common.jar!applications/uploadFrame.jsf .
This solution provided form @nambrocano  on 12th May is working.

**Comment by krishnakittu** [comment] 2019-08-23 06:41
I did the solution provided by  @nambrocano . War is deployed successfully but the context path changed.Example test.war i deployed and the application working when i hit **http://localhost:8080/test12132323232(Random Number)** instead of **http://localhost:8080/test**

**Comment by johnthad** [comment] 2019-09-14 15:38
> I did the solution provided by @nambrocano . War is deployed successfully but the context path changed.Example test.war i deployed and the application working when i hit **http://localhost:8080/test12132323232(Random Number)** instead of **http://localhost:8080/test**

In the Admin GUI, enter your app's name in the **Context Root:** input. That will deploy it without the random number.

**Comment by alagrecaPALOIT** [comment] 2019-10-02 14:51
I can't find the file uploadFrame.jsf indicated by @nambrocano

**Comment by johnthad** [comment] 2019-10-02 17:04
https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/admingui/common/src/main/resources/applications/uploadFrame.jsf

**Comment by geekonthepc** [comment] 2019-11-04 13:27
Is there any plan to fix this issue in an upcoming release? I'm hoping to migrate from 4.1.1 to 5.x in the coming months but this is a blocker for me as it's a fairly simple fix but breaks a pretty major feature.

**Comment by dzulfikriachmad** [comment] 2019-11-12 09:47
@geekonthepc you could just change the uploadFrame.jsf in console-common.jar. Maybe you'll need JD-GUI to find it and WinRAR to add it back to jar. I've tried @nambrocano solution and it works

**Comment by orlovskyjavaprofi** [comment] 2019-11-22 11:10
This bug is still there , why nobody fixed it?

**Comment by ttimot24** [comment] 2019-12-23 21:22
Same problem here, but strange, I don't think it's only a GUI issue, since my Jenkins also unable to deploy my war file.

> 22:16:38 ERROR: Build step failed with exception
22:16:38 org.codehaus.cargo.util.CargoException: Deployment has failed: null

**Comment by tastewind** [comment] 2020-01-16 02:18
> Code in uploadFrame.jsf:
> ` <sun:form id="form">`
> I probe to change it to:
> ` <sun:form id="form" enctype="multipart/form-data">`
> in uploadFrame.jsf into console-common.jar file. And it works.

It works. Thanks!

**Comment by toan12a** [comment] 2020-02-26 00:06
![image](https://user-images.githubusercontent.com/8308739/75299005-83d67580-5866-11ea-8cbe-dde594101037.png)
still error

**Comment by Akshay9882** [comment] 2020-03-21 10:22
@nambrocano In glassfish 5.0.1 in server log it is giving 
_ThreadName=admin-listener(2)] [timeMillis: 1584786012909] [levelValue: 900] [[
  StandardWrapperValve[FacesServlet]: Servlet.service() for servlet FacesServlet threw exception
java.lang.RuntimeException: Error in multipart initialization
...
...
Caused by: java.io.IOException: java.util.concurrent.TimeoutException
	at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleRead(TCPNIOTransportFilter.java:90

**Comment by johnthad** [comment] 2020-03-21 12:51
What does it take to get this bug fixed? It's been _a full year_, no one can manage to approve a v5.1.1 release?! I see there's PR (Update uploadFrame.jsf #22862) that has been _stuck for months_. I don't understand. This is most certainly *not* the way to inspire confidence in Glassfish _or_ Jarkarta-EE.

**Comment by carlosvallejos** [comment] 2020-03-23 11:55
Funciona el cambio en uploadFrame.jsf

**Comment by paooxide** [comment] 2020-04-03 19:36
There is a way to bypass this error on a browser. The solution is to change the encoding type from 
application/x-www-form-urlencoded to  multipart/form-data. 

1.  on the upload page, do inspect (**ctrl+shift+I** on Chrome Browser ) then ;
2.  find the form element and change the html form attribute **enctype** from application/x-www-form-urlencoded to  multipart/form-data
_<form id="form" enctype="application/x-www-form-urlencoded">_  (old)
<form id="form" enctype="multipart/form-data">  (**NEW**)

> now you can upload your file, fill the forms and submit. As this should deploy the WAR file 

![Screenshot (7)](https://user-images.githubusercontent.com/30201513/78398090-5a89d180-75ea-11ea-964a-1304ef91956d.png)
![Screenshot (8)](https://user-images.githubusercontent.com/30201513/78398109-683f5700-75ea-11ea-91af-f29b78822ef2.png)
![Screenshot (9)](https://user-images.githubusercontent.com/30201513/78398126-72615580-75ea-11ea-9120-0346d6b18ef1.png)
![Screenshot (10)](https://user-images.githubusercontent.com/30201513/78398194-915fe780-75ea-11ea-853a-b59be94a1634.png)

**Comment by DavidGradwell** [comment] 2020-04-06 10:36
I'm still getting this issue on a newly downloaded Glassfish 5.1.0 with Firefox as my browser.

**Comment by elisabeth-huellbusch** [comment] 2020-04-14 16:10
Same problem.

**Comment by isaarya4u** [comment] 2020-04-16 12:47
I'm facing the same problem too.
Everyone here says to edit the uploadFrame.jsf but no says how ??
can someone please explain how to edit uploadFrame.jsf.

**Comment by karlkras** [comment] 2020-04-20 19:03
Well, this work around would be fine if I could get the darn 5.1.0 release to build.

**Comment by yjinnox** [comment] 2020-04-30 14:30
> I think problem is in UploadFrame.jsf:
> `<form id="form" class="form" method="post" action="/common/applications/uploadFrame.jsf" enctype="application/x-www-form-urlencoded">`
> and could be:
> `<form id="form" class="form" method="post" action="/common/applications/uploadFrame.jsf" enctype="multipart/form-data">`
> I change it into firefox and I can upload applications without error.

Where is the uploadFrame.jsf file to modify it please

**Comment by yjinnox** [comment] 2020-04-30 14:30
@nambrocano 
Where is the uploadFrame.jsf file to modify it please

**Comment by toan12a** [comment] 2020-04-30 16:21
> @nambrocano
> Where is the uploadFrame.jsf file to modify it please

here:
glassfish/appserver/admingui/common/src/main/resources/applications/uploadFrame.jsf

**Comment by isaarya4u** [comment] 2020-04-30 16:35
Editing The uploadFrame.jsf
----------------------------
Open Glassfish Installation directory.
In my case it is as below
C:\Program Files\glassfish5\glassfish\modules\console-common.jar
1.Open console-common.jar with WinRAR
2.Open applications folder & scroll to uploadFrame.jsf
3.Right-Click on uploadFrame.jsf & select View File
4.Copy the contents of the file and paste it in notepad & save the file as uploadFrame.jsf
5.Now edit the newly created file in notepad with below mentioned changes
    <sun:form id="form"> to
    <sun:form id="form" enctype="multipart/form-data">
6.Delete the uploadFrame.jsf in applications folders and add this newly created uploadFrame.jsf

This should do!!

**Comment by geekonthepc** [comment] 2020-04-30 16:38
Is this relatively easy to fix in the project itself? Happy to open a pull request and commit a fix if this is permitted but I’m an outsider to the development project.

**Comment by geekonthepc** [comment] 2020-05-01 11:14
Looks like there's one already open.

**Comment by dboggs95** [comment] 2020-06-06 16:25
> Well, this work around would be fine if I could get the darn 5.1.0 release to build.

See this ticket. https://github.com/eclipse-ee4j/glassfish/issues/22730

I commented out the JUnit tests for libpam4j and it worked.

**Comment by dboggs95** [comment] 2020-06-06 16:26
Why isn't this marked as 5.1.1? It is a problem in 5.1.0.

**Comment by geekonthepc** [comment] 2020-06-10 10:22
This issue should now be fixed in master as I re-issued the pull request with the bug fix for the issue and it's been approved and merged.
#23089

**Closed** 2020-07-23 11:40 UTC

**Comment by kuikuijiademao** [comment] 2020-08-21 08:41
> > 我做了@nambrocano提供的解决方案。战争成功部署，但上下文路径已更改。示例test.war部署后，当我按**[http：// localhost：8080 / test12132323232（Random](http://localhost:8080/test12132323232(Random) Number）**而不是**[http：// localhost：8080 / test](http://localhost:8080/test)**时，应用程序正常运行**[](http://localhost:8080/test)**
> 
> 在管理GUI中，在“ **上下文根：”**输入中输入您的应用名称。那将部署它而没有随机数。

how to admin GUI

**Comment by Megnatis** [comment] 2023-05-12 08:36
In glassfish 7.0.3 not fixed~!

**Comment by arjantijms** [comment] 2023-05-12 11:08
> In glassfish 7.0.3 not fixed~!

What about 7.04?
